version: '3'

services:
  client:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./web:/app
      - ./core:/app/src/core
    ports:
      - "3000:3000"
  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
    - /app/node_modules
    - ./mobile:/app
    - ./core:/app/core
